/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-orb-8a81aa847da74a5cb36bd8ba13f6ae5e
Title: Cyber Orb
*/

import { useMemo, useRef, useState } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useAnimations, Decal } from '@react-three/drei'
import * as THREE from "three";


function makeTextTexture(text) {
  const size = 512;
  const c = document.createElement("canvas");
  c.width = size;
  c.height = size;
  const ctx = c.getContext("2d");

  ctx.clearRect(0, 0, size, size); // transparent background
  ctx.fillStyle = "white";
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.font = "bold 72px Arial";
  ctx.fillText(text, size / 2, size / 2);

  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.needsUpdate = true;
  return tex;
}


export default function Orb({ id = 0, label = "", position = [0, 0, 0], onSelect, ...props}) {
   const ref = useRef();
   const { nodes, materials } = useGLTF('/cyber_orb.glb');
   
   const mats = useMemo(() => {
    const shell = materials.shell.clone();
    shell.transparent = true;
    shell.opacity = 0.8;
    shell.color.set('#968cff'); 
    shell.emissive.set('#adbfff');
    shell.emissiveIntensity = 0.5;
    
    const core = materials.material.clone();;
    
    const frame = materials.frame.clone();
    frame.color.set('#e3f2ff'); 
    frame.emissive.set('#b5c4ff');
    frame.emissiveIntensity = 4;
    frame.toneMapped = true;
    
    return {
      shell,
      core,
      frame,
    };
   }, [materials]);
   
   const labelTex = useMemo(() => makeTextTexture(label), [label]);

   useFrame(({clock}) => {
    const t = clock.getElapsedTime() + id * 0.6;
    if (!ref.current) return;
    ref.current.position.y = position[1] + Math.sin(t) * 0.12;
   });


  return (
    <group ref={ref} position={position} onClick={(e) => {
        e.stopPropagation();
        onSelect?.(id);
    }}{...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sphere001_0">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={mats.shell}
                />
              </group>
              <group name="Sphere002_1" scale={0.72}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={mats.core}
                />
              </group>
              <group name="Sphere003_2" />
              <group name="Sphere004_3">
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={mats.frame}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cyber_orb.glb')
